# Generated by Django 5.0.6 on 2026-08-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Camión')),
                ('tamano', models.CharField(choices=[('GRANDE', 'Grande'), ('CHICO', 'Chico')], max_length=10, verbose_name='Tamaño')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['clave'],
            },
        ),
    ]
