# Generated by Django 5.0.6 on 2026-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ejecutivo de ventas',
                'verbose_name_plural': 'Ejecutivos de ventas',
                'ordering': ['nombre'],
            },
        ),
    ]
