# Generated by Django 5.0.6 on 2026-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaChofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Primer y Segundo turno'), ('TERCERO', 'Tercer turno')], max_length=20, verbose_name='Tipo de tarifa')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('fecha_inicio', models.DateField(verbose_name='Vigente desde')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tarifa de chofer',
                'verbose_name_plural': 'Tarifas de chofer',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
