# Generated by Django 5.0.6 on 2026-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tarifachofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoNoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Motivo')),
                ('genera_reposicion', models.BooleanField(default=True, verbose_name='Genera reposición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de no salida',
                'verbose_name_plural': 'Motivos de no salida',
                'ordering': ['nombre'],
            },
        ),
    ]
