# Generated by Django 5.0.6 on 2026-08-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_motivonosalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('fecha_orden', models.DateField(verbose_name='Fecha de la orden')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('lunes', models.BooleanField(default=False, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=False, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=False, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=False, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=False, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('recorrido', models.TextField(verbose_name='Recorrido')),
                ('perifoneo', models.BooleanField(default=False, verbose_name='Perifoneo')),
                ('firma_bitacora', models.BooleanField(default=False, verbose_name='Firma de bitácora')),
                ('evidencia_ejecutivo', models.BooleanField(default=True, verbose_name='Enviar evidencia a ejecutivo')),
                ('evidencia_grupo_choferes', models.BooleanField(default=True, verbose_name='Enviar evidencia al grupo de choferes')),
                ('evidencia_cliente', models.BooleanField(default=False, verbose_name='Enviar evidencia al cliente')),
                ('referencia_cliente', models.CharField(blank=True, max_length=150, verbose_name='Referencia del cliente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.camion', verbose_name='Camión contratado')),
                ('chofer_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_base', to='core.chofer', verbose_name='Chofer asignado')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.ejecutivo', verbose_name='Ejecutivo de ventas')),
                ('publicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.publicidad', verbose_name='Publicidad')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='core.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_orden', 'folio'],
            },
        ),
    ]
