# Generated by Django 5.0.6 on 2026-08-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ordentrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del servicio')),
                ('recorrido', models.TextField(verbose_name='Recorrido')),
                ('perifoneo', models.BooleanField(default=False, verbose_name='Perifoneo')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('hora_regreso', models.TimeField(blank=True, null=True, verbose_name='Hora de regreso')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_SERVICIO', 'En servicio'), ('REALIZADO', 'Realizado'), ('NO_SALIO', 'No salió'), ('PENDIENTE_REPOSICION', 'Pendiente de reposición'), ('REPUESTO', 'Repuesto'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=25, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('es_reposicion', models.BooleanField(default=False, verbose_name='Es reposición')),
                ('camion_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='core.camion', verbose_name='Camión contratado')),
                ('camion_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_operados', to='core.camion', verbose_name='Camión operativo')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.chofer', verbose_name='Chofer')),
                ('motivo_no_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.motivonosalida', verbose_name='Motivo de no salida')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.ordentrabajo', verbose_name='Orden de trabajo')),
                ('publicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.publicidad', verbose_name='Publicidad')),
                ('servicio_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reposiciones', to='core.servicio', verbose_name='Servicio original')),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.telefono', verbose_name='Teléfono')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha', 'turno'],
            },
        ),
    ]
